.TH "Roles" 3 "Sun Dec 18 2016" "Version 1.0.0 alpha" "Common Libs / User" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Roles \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBname\fP (string $string)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$role\fP = []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file Roles\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBname\fP (string $string)"create new role
.PP
\fBParameters:\fP
.RS 4
\fI$string\fP name of role
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 22 of file Roles\&.php\&.
.PP
.nf
                                         : RoleObject
    {
        $this->role[] = $role = new RoleObject($string);

        return $role;
    }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Common Libs / User from the source code\&.
