.TH "users" 3 "Sun Dec 18 2016" "Version 1.0.0 alpha" "Common Libs / User" \" -*- nroff -*-
.ad l
.nh
.SH NAME
users \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBlists\fP (string $orderBy='id')"
.br
.ti -1c
.RI "static \fBisUser\fP (string $username)"
.br
.ti -1c
.RI "static \fBremoveByUsername\fP (string $username)"
.br
.ti -1c
.RI "static \fBremoveById\fP (int $id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file users\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBisUser\fP (string $username)\fC [static]\fP"checks if a user exists
.PP
\fBParameters:\fP
.RS 4
\fI$username\fP Username
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 29 of file users\&.php\&.
.PP
.nf
                                                    : bool
    {
        $userdbname = setup::getValidation('username');
        if (R::findOne('user', ' ' \&. $userdbname \&. ' = ? ', [$username])) {
            return true;
        }

        return false;
    }
.fi
.SS "static \fBlists\fP (string $orderBy = \fC'id'\fP)\fC [static]\fP"Returns an array of all user beans
.PP
\fBParameters:\fP
.RS 4
\fI$orderBy\fP Order By $orderBy ASC
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 17 of file users\&.php\&.
.PP
.nf
                                                         : array
    {
        return R::findAll('user', ' ORDER BY ? ASC ', [$orderBy]);
    }
.fi
.SS "static \fBremoveById\fP (int $id)\fC [static]\fP"Removes an user by his id
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP id of user 
.RE
.PP

.PP
Definition at line 57 of file users\&.php\&.
.PP
.nf
    {
        if ($user = R::findOne('user', ' id = ? ', [$id])) {
            R::trash($user);
        }
    }
.fi
.SS "static \fBremoveByUsername\fP (string $username)\fC [static]\fP"Removes an user by his name
.PP
\fBParameters:\fP
.RS 4
\fI$username\fP Username 
.RE
.PP

.PP
Definition at line 44 of file users\&.php\&.
.PP
.nf
    {
        $userdbname = setup::getValidation('username');
        if ($user = R::findOne('user', ' ' \&. $userdbname \&. ' = ? ', [$username])) {
            R::trash($user);
        }
    }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Common Libs / User from the source code\&.
