.TH "common" 3 "Sun Dec 18 2016" "Version 1.0.0 alpha" "Common Libs / User" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBuser\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class auth
.PP
Class Config
.PP
Class BadCharactesUsernameValidationException
.PP
\fBExceptions:\fP
.RS 4
\fI\fP Class FieldNotAllowedValidationException
.br
\fI\fP Class MaxLengthValidationException
.br
\fI\fP Class MinLengthValidationException
.br
\fI\fP Class NoValidEmailValidationException
.br
\fI\fP Class RequiredValidationException
.br
\fI\fP Class UsernameTakenValidationException
.br
\fI\fP Class helper
.RE
.PP
.PP
Class auth
.PP
Class Config
.PP
Class helper
.PP
Class permission
.PP
Class role
.PP
Class RoleObject
.PP
Class Roles
.PP
Class setup
.PP
Class user
.PP
Class users
.PP
Class Validation
.PP
\\
.PP
Class ValidationObject
.PP
Class permission
.PP
Class role
.PP
Class RoleObject
.PP
Class Roles
.PP
Class setup
.PP
Class user
.PP
Class Validation
.PP
Class ValidationObject
.SH "Author"
.PP 
Generated automatically by Doxygen for Common Libs / User from the source code\&.
