.TH "common\user" 3 "Sun Dec 18 2016" "Version 1.0.0 alpha" "Common Libs / User" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common\user \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlegacy\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBauth\fP"
.br
.ti -1c
.RI "class \fBConfig\fP"
.br
.ti -1c
.RI "class \fBhelper\fP"
.br
.ti -1c
.RI "class \fBpermission\fP"
.br
.ti -1c
.RI "class \fBrole\fP"
.br
.ti -1c
.RI "class \fBRoleObject\fP"
.br
.ti -1c
.RI "class \fBRoles\fP"
.br
.ti -1c
.RI "class \fBsetup\fP"
.br
.ti -1c
.RI "class \fBuser\fP"
.br
.ti -1c
.RI "class \fBusers\fP"
.br
.ti -1c
.RI "class \fBValidation\fP"
.br
.ti -1c
.RI "class \fBValidationObject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Copyright (c) 2016 Profenter Systems
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program\&. If not, see <http://www.gnu.org/licenses/>\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Common Libs / User from the source code\&.
