var annotated =
[
    [ "auth", "classcommon_1_1user_1_1auth.html", "classcommon_1_1user_1_1auth" ],
    [ "auth", "classcommon_1_1user_1_1legacy_1_1auth.html", "classcommon_1_1user_1_1legacy_1_1auth" ],
    [ "BadCharactesUsernameValidationException", "classcommon_1_1user_1_1exception_1_1_bad_charactes_username_validation_exception.html", null ],
    [ "Config", "classcommon_1_1user_1_1_config.html", "classcommon_1_1user_1_1_config" ],
    [ "Config", "classcommon_1_1user_1_1legacy_1_1_config.html", "classcommon_1_1user_1_1legacy_1_1_config" ],
    [ "FieldNotAllowedValidationException", "classcommon_1_1user_1_1exception_1_1_field_not_allowed_validation_exception.html", null ],
    [ "helper", "classcommon_1_1user_1_1helper.html", "classcommon_1_1user_1_1helper" ],
    [ "helper", "classcommon_1_1user_1_1legacy_1_1helper.html", "classcommon_1_1user_1_1legacy_1_1helper" ],
    [ "MaxLengthValidationException", "classcommon_1_1user_1_1exception_1_1_max_length_validation_exception.html", null ],
    [ "MinLengthValidationException", "classcommon_1_1user_1_1exception_1_1_min_length_validation_exception.html", null ],
    [ "NoValidEmailValidationException", "classcommon_1_1user_1_1exception_1_1_no_valid_email_validation_exception.html", null ],
    [ "permission", "classcommon_1_1user_1_1permission.html", "classcommon_1_1user_1_1permission" ],
    [ "permission", "classcommon_1_1user_1_1legacy_1_1permission.html", "classcommon_1_1user_1_1legacy_1_1permission" ],
    [ "RequiredValidationException", "classcommon_1_1user_1_1exception_1_1_required_validation_exception.html", null ],
    [ "role", "classcommon_1_1user_1_1role.html", "classcommon_1_1user_1_1role" ],
    [ "role", "classcommon_1_1user_1_1legacy_1_1role.html", "classcommon_1_1user_1_1legacy_1_1role" ],
    [ "RoleObject", "classcommon_1_1user_1_1legacy_1_1_role_object.html", "classcommon_1_1user_1_1legacy_1_1_role_object" ],
    [ "RoleObject", "classcommon_1_1user_1_1_role_object.html", "classcommon_1_1user_1_1_role_object" ],
    [ "Roles", "classcommon_1_1user_1_1legacy_1_1_roles.html", "classcommon_1_1user_1_1legacy_1_1_roles" ],
    [ "Roles", "classcommon_1_1user_1_1_roles.html", "classcommon_1_1user_1_1_roles" ],
    [ "setup", "classcommon_1_1user_1_1legacy_1_1setup.html", "classcommon_1_1user_1_1legacy_1_1setup" ],
    [ "setup", "classcommon_1_1user_1_1setup.html", "classcommon_1_1user_1_1setup" ],
    [ "user", "classcommon_1_1user_1_1legacy_1_1user.html", "classcommon_1_1user_1_1legacy_1_1user" ],
    [ "user", "classcommon_1_1user_1_1user.html", "classcommon_1_1user_1_1user" ],
    [ "UsernameTakenValidationException", "classcommon_1_1user_1_1exception_1_1_username_taken_validation_exception.html", null ],
    [ "users", "classcommon_1_1user_1_1users.html", "classcommon_1_1user_1_1users" ],
    [ "users", "classcommon_1_1user_1_1legacy_1_1users.html", "classcommon_1_1user_1_1legacy_1_1users" ],
    [ "Validation", "classcommon_1_1user_1_1legacy_1_1_validation.html", "classcommon_1_1user_1_1legacy_1_1_validation" ],
    [ "Validation", "classcommon_1_1user_1_1_validation.html", "classcommon_1_1user_1_1_validation" ],
    [ "ValidationObject", "classcommon_1_1user_1_1_validation_object.html", "classcommon_1_1user_1_1_validation_object" ],
    [ "ValidationObject", "classcommon_1_1user_1_1legacy_1_1_validation_object.html", "classcommon_1_1user_1_1legacy_1_1_validation_object" ]
];