var files =
[
    [ "src/auth.php", null, null ],
    [ "src/Config.php", null, null ],
    [ "src/helper.php", null, null ],
    [ "src/permission.php", null, null ],
    [ "src/role.php", null, null ],
    [ "src/RoleObject.php", null, null ],
    [ "src/Roles.php", null, null ],
    [ "src/setup.php", null, null ],
    [ "src/user.php", null, null ],
    [ "src/users.php", null, null ],
    [ "src/Validation.php", null, null ],
    [ "src/ValidationObject.php", null, null ],
    [ "src/exception/BadCharactesUsernameValidationException.php", null, null ],
    [ "src/exception/FieldNotAllowedValidationException.php", null, null ],
    [ "src/exception/MaxLengthValidationException.php", null, null ],
    [ "src/exception/MinLengthValidationException.php", null, null ],
    [ "src/exception/NoValidEmailValidationException.php", null, null ],
    [ "src/exception/RequiredValidationException.php", null, null ],
    [ "src/exception/UsernameTakenValidationException.php", null, null ],
    [ "src/legacy/auth.php", null, null ],
    [ "src/legacy/Config.php", null, null ],
    [ "src/legacy/helper.php", null, null ],
    [ "src/legacy/permission.php", null, null ],
    [ "src/legacy/role.php", null, null ],
    [ "src/legacy/RoleObject.php", null, null ],
    [ "src/legacy/Roles.php", null, null ],
    [ "src/legacy/setup.php", null, null ],
    [ "src/legacy/user.php", null, null ],
    [ "src/legacy/users.php", null, null ],
    [ "src/legacy/Validation.php", null, null ],
    [ "src/legacy/ValidationObject.php", null, null ]
];